### PR TITLE
Fixes everything

### LINKED ISSUE #11: Hi
Bruh moment

### PR DESCRIPTION
**Pull request by akhiltulluri**

### CODE REVIEW

**Comment by akhiltulluri** [comment]
Closing this as no one really cares ¯\_(ツ)_/¯

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by Airbus-A330** [comment]
I sometimes get emails.

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by lorenzo132** [comment]
y

**Comment by Airbus-A330** [comment]
Hello,

Discord is focused on maintaining a safe and secure environment for our community, and your account was flagged by the Discord community for violations of our Community Guidelines.

Your account triggered our anti-spam countermeasures in one of the following ways:

* sending a large number of unsolicited DM messages in a short span of time
* participating in a server dedicated to spamming Discord users
* taking other actions on Discord — for example, joining a ton of servers — faster than humanly possible

Your actions are in violation of our Community Guidelines and are issuing you this warning.  If this behavior continues, we may take further action on your account, up to and including account termination.

Sincerely, 
Discord Trust and Safety Team

**Comment by lorenzo132** [comment]
fuck

**Comment by lorenzo132** [comment]
fbi is here

**Comment by Airbus-A330** [comment]
i feel bad for akhil

**Comment by Airbus-A330** [comment]
he's prob getting a lot of emails rn

**Comment by lorenzo132** [comment]
lmao yea

**Comment by lorenzo132** [comment]
just apologized 2 him for if he has notifications enabled

**Comment by Airbus-A330** [comment]
am sorry akhil

**Comment by Airbus-A330** [comment]
ok guys ok guys ok guys discord has this jnew feature outline replies

**Comment by Airbus-A330** [comment]
we're gonna leave this open so y'all can shitpost to it until we merge it and yeah

**Comment by Airbus-A330** [comment]
here's a picture of it in action

**Comment by Airbus-A330** [comment]
image

**Comment by akhiltulluri** [comment]
> am sorry akhil

You better be

**Comment by akhiltulluri** [comment]
> just apologized 2 him for if he has notifications enabled

👀

**Comment by Airbus-A330** [comment]
Okay

**Pull request closed without merging**
